---
variables:
  dataset: &dataset %(dataset)s
  backbone: &backbone Conv4
  method: &method %(method)s
  train_aug: &train_aug True
  train_n_way: &train_n_way %(train_n_way)s
  test_n_way: &test_n_way %(test_n_way)s
  n_shot: &n_shot %(n_shot)s
  split: &split novel
  save_iter: &save_iter -1
  random_seed: &random_seed 96

init:

  flows:

    method_training_flow:
      steps:
      - name: MethodTraining
        init:
          dataset: *dataset
          backbone: *backbone
          method: *method
          train_aug: *train_aug
          train_n_way: *train_n_way
          test_n_way: *test_n_way
          n_shot: *n_shot
          random_seed: *random_seed
          num_classes: 4412
          stop_epoch: 2
          start_epoch: 0
          shallow: False
          resume: False
          warmup: False
          optimizer: Adam
          learning_rate: 0.001
          n_episode: 100

    embedding_flow:
      inputs: method_training_flow
      steps:
      - name: Embedding
        init:
          dataset: *dataset
          backbone: *backbone
          method: *method
          train_n_way: *train_n_way
          test_n_way: *test_n_way
          n_shot: *n_shot
          train_aug: *train_aug
          split: *split
          save_iter: *save_iter
          random_seed: *random_seed
          shallow: False

    method_evaluation_flow_0swap:
      inputs:
        - method_training_flow
        - embedding_flow
      steps:
        - name: MethodEvaluation
          init:
            dataset: *dataset
            backbone: *backbone
            method: *method
            train_n_way: *train_n_way
            test_n_way: *test_n_way
            n_shot: *n_shot
            train_aug: *train_aug
            split: *split
            save_iter: *save_iter
            random_seed: *random_seed
            n_iter: 600
            adaptation: False
            n_swaps: 0

    method_evaluation_flow_3swap:
      inputs:
        - method_training_flow
        - embedding_flow
      steps:
        - name: MethodEvaluation
          init:
            dataset: *dataset
            backbone: *backbone
            method: *method
            train_n_way: *train_n_way
            test_n_way: *test_n_way
            n_shot: *n_shot
            train_aug: *train_aug
            split: *split
            save_iter: *save_iter
            random_seed: *random_seed
            n_iter: 600
            adaptation: False
            n_swaps: 3

    method_evaluation_flow_6swap:
      inputs:
        - method_training_flow
        - embedding_flow
      steps:
        - name: MethodEvaluation
          init:
            dataset: *dataset
            backbone: *backbone
            method: *method
            train_n_way: *train_n_way
            test_n_way: *test_n_way
            n_shot: *n_shot
            train_aug: *train_aug
            split: *split
            save_iter: *save_iter
            random_seed: *random_seed
            n_iter: 600
            adaptation: False
            n_swaps: 6

    method_evaluation_flow_10swap:
      inputs:
        - method_training_flow
        - embedding_flow
      steps:
        - name: MethodEvaluation
          init:
            dataset: *dataset
            backbone: *backbone
            method: *method
            train_n_way: *train_n_way
            test_n_way: *test_n_way
            n_shot: *n_shot
            train_aug: *train_aug
            split: *split
            save_iter: *save_iter
            random_seed: *random_seed
            n_iter: 600
            adaptation: False
            n_swaps: 10


run:
  output_folder: output
  output_folder_permissions: 02775
