---
init:

  flows:

    training_flow:
      steps:
      - name: YOLOMAMLTraining
        init:
          dataset_config: pipelines/detection/experiments_config/coco.data
          model_config: pipelines/detection/experiments_config/deep-tiny-yolo-5-way.cfg
          pretrained_weights: ./data/weights/tiny.weights
          n_way: 5
          n_shot: 5
          n_query: 10
          optimizer: Adam
          learning_rate: 0.01
          approx: True
          n_task: 1
          task_update_num: 1
          print_freq: 1
          n_epoch: 50
          n_episode: 200
          objectness_threshold: 0.5
          nms_threshold: 0.3
          iou_threshold: 0.5
          image_size: 208

run:
  output_folder: output
  output_folder_permissions: 02775
