---
init:

  flows:

    training_flow:
      steps:
      - name: YOLOMAMLTraining
        init:
          dataset_config: pipelines/detection/experiments_config/coco.data
          model_config: pipelines/detection/experiments_config/deep-tiny-yolo-3-way.cfg
          pretrained_weights: ./data/weights/tiny.weights
          n_way: 3
          n_shot: 5
          n_query: 10
          optimizer: Adam
          learning_rate: 0.001
          approx: True
          task_update_num: 2
          n_epoch: 100000
          n_episode: 4
          validation_freq: 5000
          objectness_threshold: 0.5
          nms_threshold: 0.3
          iou_threshold: 0.5
          image_size: 208

run:
  output_folder: output
  output_folder_permissions: 02775
