---
init:

  flows:

    training_flow:
      steps:
      - name: YOLOTraining
        init:
          dataset_config: pipelines/detection/experiments_config/coco.data
          model_config: pipelines/detection/experiments_config/deep-tiny-yolo-80-way.cfg
          pretrained_weights: ./data/weights/tiny.weights
          optimizer: Adam
          learning_rate: 0.001
          n_epoch: 1
          validation_freq: 500
          objectness_threshold: 0.5
          nms_threshold: 0.3
          iou_threshold: 0.5
          image_size: 208

run:
  output_folder: output
  output_folder_permissions: 02775
